- hosts: localhost
  become: yes
  tasks:
    - name: Stop old container
      shell: docker stop feedback-app || true

    - name: Remove old container
      shell: docker rm feedback-app || true

    - name: Remove old image (optional)
      shell: docker rmi student-feedback-app || true

    - name: Build Docker image
      shell: docker build -t student-feedback-app .

    - name: Run container
      shell: docker run -d -p 5000:5000 --name feedback-app student-feedback-app
